name: iOS Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Flutter info
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: CocoaPods install
        working-directory: ios
        run: |
          pod repo update
          pod install

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 Beta.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Beta-iOS
          path: build/ios/iphoneos/Beta.ipa
          retention-days: 30
